shellEmulator: true
trustPolicy: no-downgrade
packages:
  - packages/*
overrides:
  chokidar: ^5.0.0
  eslint: ^9.39.2
  glob: ^13.0.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
